package_info_mock_results <- list(
  # package_info("dplyr") |> dput() |> capture.output() |> clipr::write_clip()
  dplyr = structure(
    list(
      package = c(
        "cli",
        "dplyr",
        "fansi",
        "generics",
        "glue",
        "lifecycle",
        "magrittr",
        "pillar",
        "pkgconfig",
        "R6",
        "rlang",
        "tibble",
        "tidyselect",
        "utf8",
        "vctrs",
        "withr"
      ),
      ondiskversion = c(
        "3.6.4",
        "1.1.4",
        "1.0.6",
        "0.1.3",
        "1.8.0",
        "1.0.4",
        "2.0.3",
        "1.10.1",
        "2.0.3",
        "2.6.1",
        "1.1.5",
        "3.2.1",
        "1.2.1",
        "1.2.4",
        "0.6.5",
        "3.0.2"
      ),
      loadedversion = c(
        "3.6.4",
        "1.1.4",
        NA,
        "0.1.3",
        "1.8.0",
        "1.0.4",
        "2.0.3",
        "1.10.1",
        "2.0.3",
        "2.6.1",
        "1.1.5",
        "3.2.1",
        "1.2.1",
        "1.2.4",
        "0.6.5",
        "3.0.2"
      ),
      path = c(
        "/Users/garrick/Library/R/arm64/4.4/library/cli",
        "/Users/garrick/Library/R/arm64/4.4/library/dplyr",
        "/Users/garrick/Library/R/arm64/4.4/library/fansi",
        "/Users/garrick/Library/R/arm64/4.4/library/generics",
        "/Users/garrick/Library/R/arm64/4.4/library/glue",
        "/Users/garrick/Library/R/arm64/4.4/library/lifecycle",
        "/Users/garrick/Library/R/arm64/4.4/library/magrittr",
        "/Users/garrick/Library/R/arm64/4.4/library/pillar",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgconfig",
        "/Users/garrick/Library/R/arm64/4.4/library/R6",
        "/Users/garrick/Library/R/arm64/4.4/library/rlang",
        "/Users/garrick/Library/R/arm64/4.4/library/tibble",
        "/Users/garrick/Library/R/arm64/4.4/library/tidyselect",
        "/Users/garrick/Library/R/arm64/4.4/library/utf8",
        "/Users/garrick/Library/R/arm64/4.4/library/vctrs",
        "/Users/garrick/Library/R/arm64/4.4/library/withr"
      ),
      loadedpath = c(
        "/Users/garrick/Library/R/arm64/4.4/library/cli",
        "/Users/garrick/Library/R/arm64/4.4/library/dplyr",
        NA,
        "/Users/garrick/Library/R/arm64/4.4/library/generics",
        "/Users/garrick/Library/R/arm64/4.4/library/glue",
        "/Users/garrick/Library/R/arm64/4.4/library/lifecycle",
        "/Users/garrick/Library/R/arm64/4.4/library/magrittr",
        "/Users/garrick/Library/R/arm64/4.4/library/pillar",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgconfig",
        "/Users/garrick/Library/R/arm64/4.4/library/R6",
        "/Users/garrick/Library/R/arm64/4.4/library/rlang",
        "/Users/garrick/Library/R/arm64/4.4/library/tibble",
        "/Users/garrick/Library/R/arm64/4.4/library/tidyselect",
        "/Users/garrick/Library/R/arm64/4.4/library/utf8",
        "/Users/garrick/Library/R/arm64/4.4/library/vctrs",
        "/Users/garrick/Library/R/arm64/4.4/library/withr"
      ),
      attached = c(
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE
      ),
      is_base = c(
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE
      ),
      date = c(
        "2025-02-13",
        "2023-11-17",
        "2023-12-08",
        "2022-07-05",
        "2024-09-30",
        "2023-11-07",
        "2022-03-30",
        "2025-01-07",
        "2019-09-22",
        "2025-02-15",
        "2025-01-17",
        "2023-03-20",
        "2024-03-11",
        "2023-10-22",
        "2023-12-01",
        "2024-10-28"
      ),
      source = c(
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)"
      ),
      md5ok = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
      library = structure(
        c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L),
        levels = c(
          "/Users/garrick/Library/R/arm64/4.4/library",
          "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
        ),
        class = "factor"
      )
    ),
    row.names = c(
      "cli",
      "dplyr",
      "fansi",
      "generics",
      "glue",
      "lifecycle",
      "magrittr",
      "pillar",
      "pkgconfig",
      "R6",
      "rlang",
      "tibble",
      "tidyselect",
      "utf8",
      "vctrs",
      "withr"
    ),
    class = c("packages_info", "data.frame")
  ),
  # package_info("digest", dependencies = c("Imports", "Suggests")) |> dput() |> capture.output() |> clipr::write_clip()
  "digest" = structure(
    list(
      package = c("digest", "simplermarkdown", "tinytest"),
      ondiskversion = c("0.6.37", NA, NA),
      loadedversion = c("0.6.37", NA, NA),
      path = c("/Users/garrick/Library/R/arm64/4.4/library/digest", NA, NA),
      loadedpath = c(
        "/Users/garrick/Library/R/arm64/4.4/library/digest",
        NA,
        NA
      ),
      attached = c(FALSE, FALSE, FALSE),
      is_base = c(FALSE, FALSE, FALSE),
      date = c("2024-08-19", NA, NA),
      source = c("CRAN (R 4.4.1)", NA, NA),
      md5ok = c(NA, NA, NA),
      library = structure(
        c(1L, NA, NA),
        levels = c(
          "/Users/garrick/Library/R/arm64/4.4/library",
          "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
        ),
        class = "factor"
      )
    ),
    row.names = c("digest", "simplermarkdown", "tinytest"),
    class = c("packages_info", "data.frame")
  ),
  "attached" = structure(
    list(
      package = c("btw", "devtools", "testthat", "usethis"),
      ondiskversion = c("0.0.0.9001", "2.4.5", "3.2.3", "2.2.3"),
      loadedversion = c("0.0.0.9001", "2.4.5", "3.2.3", "2.2.3"),
      path = c(
        "/Users/garrick/Library/R/arm64/4.4/library/btw",
        "/Users/garrick/Library/R/arm64/4.4/library/devtools",
        "/Users/garrick/Library/R/arm64/4.4/library/testthat",
        "/Users/garrick/Library/R/arm64/4.4/library/usethis"
      ),
      loadedpath = c(
        "/Users/garrick/work/posit-dev/btw",
        "/Users/garrick/Library/R/arm64/4.4/library/devtools",
        "/Users/garrick/Library/R/arm64/4.4/library/testthat",
        "/Users/garrick/Library/R/arm64/4.4/library/usethis"
      ),
      attached = c(TRUE, TRUE, TRUE, TRUE),
      is_base = c(FALSE, FALSE, FALSE, FALSE),
      date = c("2025-03-21", "2022-10-11", "2025-01-30", "2024-02-19"),
      source = c(
        "Github (posit-dev/btw@cfb84d4c10f7706b99845f104b91d543f4aa3d69)",
        "CRAN (R 4.4.0)",
        "Github (r-lib/testthat@50a99ec76fed8140a9211ed862289e877e86614d)",
        "CRAN (R 4.4.0)"
      ),
      md5ok = c(NA, NA, NA, NA),
      library = structure(
        c(NA, 1L, 1L, 1L),
        levels = c(
          "/Users/garrick/Library/R/arm64/4.4/library",
          "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
        ),
        class = "factor"
      )
    ),
    row.names = c("btw", "devtools", "testthat", "usethis"),
    class = c("packages_info", "data.frame")
  ),
  "loaded" = structure(
    list(
      package = c(
        "base64enc",
        "brio",
        "btw",
        "cachem",
        "cli",
        "clipr",
        "coro",
        "desc",
        "devtools",
        "digest",
        "dplyr",
        "ellipsis",
        "ellmer",
        "evaluate",
        "fastmap",
        "fs",
        "generics",
        "glue",
        "grkstyle",
        "htmltools",
        "htmlwidgets",
        "httpuv",
        "httr2",
        "jsonlite",
        "knitr",
        "later",
        "lifecycle",
        "magrittr",
        "memoise",
        "mime",
        "miniUI",
        "pillar",
        "pkgbuild",
        "pkgconfig",
        "pkgload",
        "praise",
        "profvis",
        "promises",
        "purrr",
        "R6",
        "rappdirs",
        "Rcpp",
        "remotes",
        "repr",
        "rlang",
        "rmarkdown",
        "roxygen2",
        "rprojroot",
        "rsthemes",
        "rstudioapi",
        "S7",
        "sessioninfo",
        "shiny",
        "shrtcts",
        "skimr",
        "stringi",
        "stringr",
        "testthat",
        "tibble",
        "tidyselect",
        "urlchecker",
        "usethis",
        "vctrs",
        "withr",
        "xfun",
        "xml2",
        "xtable"
      ),
      ondiskversion = c(
        "0.1.3",
        "1.1.5",
        "0.0.0.9001",
        "1.1.0",
        "3.6.4",
        "0.8.0",
        "1.1.0",
        "1.4.3",
        "2.4.5",
        "0.6.37",
        "1.1.4",
        "0.3.2",
        "0.1.1",
        "1.0.3",
        "1.2.0",
        "1.6.5",
        "0.1.3",
        "1.8.0",
        "0.2.1",
        "0.5.8.1",
        "1.6.4",
        "1.6.15",
        "1.1.1",
        "1.9.1",
        "1.50",
        "1.4.1",
        "1.0.4",
        "2.0.3",
        "2.0.1",
        "0.13",
        "0.1.1.1",
        "1.10.1",
        "1.4.6",
        "2.0.3",
        "1.4.0",
        "1.0.0",
        "0.3.8",
        "1.3.2",
        "1.0.4",
        "2.6.1",
        "0.3.3",
        "1.0.14",
        "2.5.0.9000",
        "1.1.7",
        "1.1.5",
        "2.29",
        "7.3.2",
        "2.0.4",
        "0.4.0",
        "0.17.1",
        "0.2.0",
        "1.2.3",
        "1.10.0.9000",
        "0.1.2.9000",
        "2.1.5",
        "1.8.4",
        "1.5.1",
        "3.2.3",
        "3.2.1",
        "1.2.1",
        "1.0.1",
        "2.2.3",
        "0.6.5",
        "3.0.2",
        "0.51",
        "1.3.8",
        "1.8.4"
      ),
      loadedversion = c(
        "0.1-3",
        "1.1.5",
        "0.0.0.9001",
        "1.1.0",
        "3.6.4",
        "0.8.0",
        "1.1.0",
        "1.4.3",
        "2.4.5",
        "0.6.37",
        "1.1.4",
        "0.3.2",
        "0.1.1",
        "1.0.3",
        "1.2.0",
        "1.6.5",
        "0.1.3",
        "1.8.0",
        "0.2.1",
        "0.5.8.1",
        "1.6.4",
        "1.6.15",
        "1.1.1",
        "1.9.1",
        "1.50",
        "1.4.1",
        "1.0.4",
        "2.0.3",
        "2.0.1",
        "0.13",
        "0.1.1.1",
        "1.10.1",
        "1.4.6",
        "2.0.3",
        "1.4.0",
        "1.0.0",
        "0.3.8",
        "1.3.2",
        "1.0.4",
        "2.6.1",
        "0.3.3",
        "1.0.14",
        "2.5.0.9000",
        "1.1.7",
        "1.1.5",
        "2.29",
        "7.3.2",
        "2.0.4",
        "0.4.0",
        "0.17.1",
        "0.2.0",
        "1.2.3",
        "1.10.0.9000",
        "0.1.2.9000",
        "2.1.5",
        "1.8.4",
        "1.5.1",
        "3.2.3",
        "3.2.1",
        "1.2.1",
        "1.0.1",
        "2.2.3",
        "0.6.5",
        "3.0.2",
        "0.51",
        "1.3.8",
        "1.8-4"
      ),
      path = c(
        "/Users/garrick/Library/R/arm64/4.4/library/base64enc",
        "/Users/garrick/Library/R/arm64/4.4/library/brio",
        "/Users/garrick/Library/R/arm64/4.4/library/btw",
        "/Users/garrick/Library/R/arm64/4.4/library/cachem",
        "/Users/garrick/Library/R/arm64/4.4/library/cli",
        "/Users/garrick/Library/R/arm64/4.4/library/clipr",
        "/Users/garrick/Library/R/arm64/4.4/library/coro",
        "/Users/garrick/Library/R/arm64/4.4/library/desc",
        "/Users/garrick/Library/R/arm64/4.4/library/devtools",
        "/Users/garrick/Library/R/arm64/4.4/library/digest",
        "/Users/garrick/Library/R/arm64/4.4/library/dplyr",
        "/Users/garrick/Library/R/arm64/4.4/library/ellipsis",
        "/Users/garrick/Library/R/arm64/4.4/library/ellmer",
        "/Users/garrick/Library/R/arm64/4.4/library/evaluate",
        "/Users/garrick/Library/R/arm64/4.4/library/fastmap",
        "/Users/garrick/Library/R/arm64/4.4/library/fs",
        "/Users/garrick/Library/R/arm64/4.4/library/generics",
        "/Users/garrick/Library/R/arm64/4.4/library/glue",
        "/Users/garrick/Library/R/arm64/4.4/library/grkstyle",
        "/Users/garrick/Library/R/arm64/4.4/library/htmltools",
        "/Users/garrick/Library/R/arm64/4.4/library/htmlwidgets",
        "/Users/garrick/Library/R/arm64/4.4/library/httpuv",
        "/Users/garrick/Library/R/arm64/4.4/library/httr2",
        "/Users/garrick/Library/R/arm64/4.4/library/jsonlite",
        "/Users/garrick/Library/R/arm64/4.4/library/knitr",
        "/Users/garrick/Library/R/arm64/4.4/library/later",
        "/Users/garrick/Library/R/arm64/4.4/library/lifecycle",
        "/Users/garrick/Library/R/arm64/4.4/library/magrittr",
        "/Users/garrick/Library/R/arm64/4.4/library/memoise",
        "/Users/garrick/Library/R/arm64/4.4/library/mime",
        "/Users/garrick/Library/R/arm64/4.4/library/miniUI",
        "/Users/garrick/Library/R/arm64/4.4/library/pillar",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgbuild",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgconfig",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgload",
        "/Users/garrick/Library/R/arm64/4.4/library/praise",
        "/Users/garrick/Library/R/arm64/4.4/library/profvis",
        "/Users/garrick/Library/R/arm64/4.4/library/promises",
        "/Users/garrick/Library/R/arm64/4.4/library/purrr",
        "/Users/garrick/Library/R/arm64/4.4/library/R6",
        "/Users/garrick/Library/R/arm64/4.4/library/rappdirs",
        "/Users/garrick/Library/R/arm64/4.4/library/Rcpp",
        "/Users/garrick/Library/R/arm64/4.4/library/remotes",
        "/Users/garrick/Library/R/arm64/4.4/library/repr",
        "/Users/garrick/Library/R/arm64/4.4/library/rlang",
        "/Users/garrick/Library/R/arm64/4.4/library/rmarkdown",
        "/Users/garrick/Library/R/arm64/4.4/library/roxygen2",
        "/Users/garrick/Library/R/arm64/4.4/library/rprojroot",
        "/Users/garrick/Library/R/arm64/4.4/library/rsthemes",
        "/Users/garrick/Library/R/arm64/4.4/library/rstudioapi",
        "/Users/garrick/Library/R/arm64/4.4/library/S7",
        "/Users/garrick/Library/R/arm64/4.4/library/sessioninfo",
        "/Users/garrick/Library/R/arm64/4.4/library/shiny",
        "/Users/garrick/Library/R/arm64/4.4/library/shrtcts",
        "/Users/garrick/Library/R/arm64/4.4/library/skimr",
        "/Users/garrick/Library/R/arm64/4.4/library/stringi",
        "/Users/garrick/Library/R/arm64/4.4/library/stringr",
        "/Users/garrick/Library/R/arm64/4.4/library/testthat",
        "/Users/garrick/Library/R/arm64/4.4/library/tibble",
        "/Users/garrick/Library/R/arm64/4.4/library/tidyselect",
        "/Users/garrick/Library/R/arm64/4.4/library/urlchecker",
        "/Users/garrick/Library/R/arm64/4.4/library/usethis",
        "/Users/garrick/Library/R/arm64/4.4/library/vctrs",
        "/Users/garrick/Library/R/arm64/4.4/library/withr",
        "/Users/garrick/Library/R/arm64/4.4/library/xfun",
        "/Users/garrick/Library/R/arm64/4.4/library/xml2",
        "/Users/garrick/Library/R/arm64/4.4/library/xtable"
      ),
      loadedpath = c(
        "/Users/garrick/Library/R/arm64/4.4/library/base64enc",
        "/Users/garrick/Library/R/arm64/4.4/library/brio",
        "/Users/garrick/work/posit-dev/btw",
        "/Users/garrick/Library/R/arm64/4.4/library/cachem",
        "/Users/garrick/Library/R/arm64/4.4/library/cli",
        "/Users/garrick/Library/R/arm64/4.4/library/clipr",
        "/Users/garrick/Library/R/arm64/4.4/library/coro",
        "/Users/garrick/Library/R/arm64/4.4/library/desc",
        "/Users/garrick/Library/R/arm64/4.4/library/devtools",
        "/Users/garrick/Library/R/arm64/4.4/library/digest",
        "/Users/garrick/Library/R/arm64/4.4/library/dplyr",
        "/Users/garrick/Library/R/arm64/4.4/library/ellipsis",
        "/Users/garrick/Library/R/arm64/4.4/library/ellmer",
        "/Users/garrick/Library/R/arm64/4.4/library/evaluate",
        "/Users/garrick/Library/R/arm64/4.4/library/fastmap",
        "/Users/garrick/Library/R/arm64/4.4/library/fs",
        "/Users/garrick/Library/R/arm64/4.4/library/generics",
        "/Users/garrick/Library/R/arm64/4.4/library/glue",
        "/Users/garrick/Library/R/arm64/4.4/library/grkstyle",
        "/Users/garrick/Library/R/arm64/4.4/library/htmltools",
        "/Users/garrick/Library/R/arm64/4.4/library/htmlwidgets",
        "/Users/garrick/Library/R/arm64/4.4/library/httpuv",
        "/Users/garrick/Library/R/arm64/4.4/library/httr2",
        "/Users/garrick/Library/R/arm64/4.4/library/jsonlite",
        "/Users/garrick/Library/R/arm64/4.4/library/knitr",
        "/Users/garrick/Library/R/arm64/4.4/library/later",
        "/Users/garrick/Library/R/arm64/4.4/library/lifecycle",
        "/Users/garrick/Library/R/arm64/4.4/library/magrittr",
        "/Users/garrick/Library/R/arm64/4.4/library/memoise",
        "/Users/garrick/Library/R/arm64/4.4/library/mime",
        "/Users/garrick/Library/R/arm64/4.4/library/miniUI",
        "/Users/garrick/Library/R/arm64/4.4/library/pillar",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgbuild",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgconfig",
        "/Users/garrick/Library/R/arm64/4.4/library/pkgload",
        "/Users/garrick/Library/R/arm64/4.4/library/praise",
        "/Users/garrick/Library/R/arm64/4.4/library/profvis",
        "/Users/garrick/Library/R/arm64/4.4/library/promises",
        "/Users/garrick/Library/R/arm64/4.4/library/purrr",
        "/Users/garrick/Library/R/arm64/4.4/library/R6",
        "/Users/garrick/Library/R/arm64/4.4/library/rappdirs",
        "/Users/garrick/Library/R/arm64/4.4/library/Rcpp",
        "/Users/garrick/Library/R/arm64/4.4/library/remotes",
        "/Users/garrick/Library/R/arm64/4.4/library/repr",
        "/Users/garrick/Library/R/arm64/4.4/library/rlang",
        "/Users/garrick/Library/R/arm64/4.4/library/rmarkdown",
        "/Users/garrick/Library/R/arm64/4.4/library/roxygen2",
        "/Users/garrick/Library/R/arm64/4.4/library/rprojroot",
        "/Users/garrick/Library/R/arm64/4.4/library/rsthemes",
        "/Users/garrick/Library/R/arm64/4.4/library/rstudioapi",
        "/Users/garrick/Library/R/arm64/4.4/library/S7",
        "/Users/garrick/Library/R/arm64/4.4/library/sessioninfo",
        "/Users/garrick/Library/R/arm64/4.4/library/shiny",
        "/Users/garrick/Library/R/arm64/4.4/library/shrtcts",
        "/Users/garrick/Library/R/arm64/4.4/library/skimr",
        "/Users/garrick/Library/R/arm64/4.4/library/stringi",
        "/Users/garrick/Library/R/arm64/4.4/library/stringr",
        "/Users/garrick/Library/R/arm64/4.4/library/testthat",
        "/Users/garrick/Library/R/arm64/4.4/library/tibble",
        "/Users/garrick/Library/R/arm64/4.4/library/tidyselect",
        "/Users/garrick/Library/R/arm64/4.4/library/urlchecker",
        "/Users/garrick/Library/R/arm64/4.4/library/usethis",
        "/Users/garrick/Library/R/arm64/4.4/library/vctrs",
        "/Users/garrick/Library/R/arm64/4.4/library/withr",
        "/Users/garrick/Library/R/arm64/4.4/library/xfun",
        "/Users/garrick/Library/R/arm64/4.4/library/xml2",
        "/Users/garrick/Library/R/arm64/4.4/library/xtable"
      ),
      attached = c(
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE
      ),
      is_base = c(
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        FALSE
      ),
      date = c(
        "2015-07-28",
        "2024-04-24",
        "2025-03-21",
        "2024-05-16",
        "2025-02-13",
        "2022-02-22",
        "2024-11-05",
        "2023-12-10",
        "2022-10-11",
        "2024-08-19",
        "2023-11-17",
        "2021-04-29",
        "2025-02-07",
        "2025-01-10",
        "2024-05-15",
        "2024-10-30",
        "2022-07-05",
        "2024-09-30",
        "2024-03-21",
        "2024-04-04",
        "2023-12-06",
        "2024-03-26",
        "2025-03-08",
        "2025-03-03",
        "2025-03-16",
        "2024-11-27",
        "2023-11-07",
        "2022-03-30",
        "2021-11-26",
        "2025-03-17",
        "2018-05-18",
        "2025-01-07",
        "2025-01-16",
        "2019-09-22",
        "2024-06-28",
        "2015-08-11",
        "2023-05-02",
        "2024-11-28",
        "2025-02-05",
        "2025-02-15",
        "2021-01-31",
        "2025-01-12",
        "2025-02-03",
        "2024-03-22",
        "2025-01-17",
        "2024-11-04",
        "2024-06-28",
        "2023-11-05",
        "2024-03-13",
        "2024-10-22",
        "2024-11-07",
        "2025-02-05",
        "2025-02-26",
        "2025-01-22",
        "2022-12-23",
        "2024-05-06",
        "2023-11-14",
        "2025-01-30",
        "2023-03-20",
        "2024-03-11",
        "2021-11-30",
        "2024-02-19",
        "2023-12-01",
        "2024-10-28",
        "2025-02-19",
        "2025-03-14",
        "2019-04-21"
      ),
      source = c(
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "Github (posit-dev/btw@cfb84d4c10f7706b99845f104b91d543f4aa3d69)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.2)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "https://g~",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.2)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.2)",
        "Github (MangoTheCat/remotes@39a6a813bbbb3df2780280a3613bc4ecc31bc1fc)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "any (@2.29)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "https://g~",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.1)",
        "Github (rstudio/shiny@531f31b66f0d83d07341b5e88e33386e4dc10f3e)",
        "https://g~",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "Github (r-lib/testthat@50a99ec76fed8140a9211ed862289e877e86614d)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.0)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.2)",
        "CRAN (R 4.4.1)",
        "CRAN (R 4.4.0)"
      ),
      md5ok = c(
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA
      ),
      library = structure(
        c(
          1L,
          1L,
          NA,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L,
          1L
        ),
        levels = c(
          "/Users/garrick/Library/R/arm64/4.4/library",
          "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
        ),
        class = "factor"
      )
    ),
    row.names = c(
      "base64enc",
      "brio",
      "btw",
      "cachem",
      "cli",
      "clipr",
      "coro",
      "desc",
      "devtools",
      "digest",
      "dplyr",
      "ellipsis",
      "ellmer",
      "evaluate",
      "fastmap",
      "fs",
      "generics",
      "glue",
      "grkstyle",
      "htmltools",
      "htmlwidgets",
      "httpuv",
      "httr2",
      "jsonlite",
      "knitr",
      "later",
      "lifecycle",
      "magrittr",
      "memoise",
      "mime",
      "miniUI",
      "pillar",
      "pkgbuild",
      "pkgconfig",
      "pkgload",
      "praise",
      "profvis",
      "promises",
      "purrr",
      "R6",
      "rappdirs",
      "Rcpp",
      "remotes",
      "repr",
      "rlang",
      "rmarkdown",
      "roxygen2",
      "rprojroot",
      "rsthemes",
      "rstudioapi",
      "S7",
      "sessioninfo",
      "shiny",
      "shrtcts",
      "skimr",
      "stringi",
      "stringr",
      "testthat",
      "tibble",
      "tidyselect",
      "urlchecker",
      "usethis",
      "vctrs",
      "withr",
      "xfun",
      "xml2",
      "xtable"
    ),
    class = c("packages_info", "data.frame")
  ),
  # package_info(c("dplyr", "tidyr"), dependencies = FALSE) |> dput() |> capture.output() |> clipr::write_clip()
  "dplyr,tidyr" = structure(
    list(
      package = c("dplyr", "tidyr"),
      ondiskversion = c("1.1.4", "1.3.1"),
      loadedversion = c("1.1.4", NA),
      path = c(
        "/Users/garrick/Library/R/arm64/4.4/library/dplyr",
        "/Users/garrick/Library/R/arm64/4.4/library/tidyr"
      ),
      loadedpath = c("/Users/garrick/Library/R/arm64/4.4/library/dplyr", NA),
      attached = c(FALSE, FALSE),
      is_base = c(FALSE, FALSE),
      date = c("2023-11-17", "2024-01-24"),
      source = c("CRAN (R 4.4.0)", "CRAN (R 4.4.0)"),
      md5ok = c(NA, NA),
      library = structure(
        c(1L, 1L),
        levels = c(
          "/Users/garrick/Library/R/arm64/4.4/library",
          "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
        ),
        class = "factor"
      )
    ),
    row.names = c("dplyr", "tidyr"),
    class = c("packages_info", "data.frame")
  )
)
